name: financial_app
description: "Personal Financial Tracker App with Flutter & Firebase"
publish_to: 'none'
version: 1.0.3+4

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase
  firebase_core: ^4.11.0
  firebase_auth: ^6.5.4
  cloud_firestore: ^6.6.0
  firebase_analytics: ^12.4.3
  firebase_crashlytics: ^5.2.4
  firebase_messaging: ^16.4.1
  flutter_local_notifications: ^22.0.1
  
  # Local Database
  sqflite: ^2.3.3+2
  path: ^1.9.0
  
  # State Management
  flutter_riverpod: ^3.3.2
  riverpod_annotation: ^4.0.3
  
  # Connectivity
  connectivity_plus: ^7.2.0
  
  # UI
  cupertino_icons: ^1.0.8
  flutter_localizations:
    sdk: flutter
  intl: 0.20.2
  
  # Charts
  fl_chart: ^1.2.0
  
  # Utils
  uuid: ^4.5.1
  dio: ^5.7.0
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  shared_preferences: ^2.5.3
  package_info_plus: ^10.2.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.1
  
  # Code Generation
  build_runner: ^2.4.13
  freezed: ^3.2.6-dev.1
  json_serializable: ^6.8.0
  riverpod_generator: ^4.0.4
  
  # Testing
  sqflite_common_ffi: ^2.3.3
  
flutter:
  uses-material-design: true
  generate: true
  
  assets:
    - assets/icon/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icon/app_icon.png"
  
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
